#!/usr/bin/env python3
"""Generate init.sql for holoscrape's sharded MySQL schema.

Usage:
    python resources/generate_init_sql.py [--nshards 30] [--table chat_tab] [--stream-table stream_tab]
"""

import argparse
import sys

TEMPLATE = """\
-- holoscrape database schema
-- Generated by generate_init_sql.py
-- Shards: {nshards}, chat table: {table}, stream table: {stream_table}

CREATE USER 'holoscrape'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON holoscrape.* TO 'holoscrape'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS holoscrape;
USE holoscrape;

"""

SHARD_TEMPLATE = """\
CREATE TABLE IF NOT EXISTS {table}_{i} (
\tvideo_id VARCHAR(255),
\tchat_id VARCHAR(255) NOT NULL PRIMARY KEY,
\ttext VARCHAR(255),
\ttimestamp VARCHAR(255),
\tauthor_name VARCHAR(255),
\tauthor_id VARCHAR(255),
\tsource VARCHAR(255)
);

"""

STREAM_TABLE_TEMPLATE = """\
CREATE TABLE IF NOT EXISTS {stream_table} (
\tid VARCHAR(255) NOT NULL PRIMARY KEY,
\ttitle VARCHAR(255),
\ttopic_id VARCHAR(255),
\tchannel_id VARCHAR(255),
\tchannel_name VARCHAR(255)
);
"""


def generate(nshards: int, table: str, stream_table: str) -> str:
    """Generate the full SQL schema as a string."""
    sql = TEMPLATE.format(nshards=nshards, table=table, stream_table=stream_table)
    for i in range(nshards):
        sql += SHARD_TEMPLATE.format(table=table, i=i)
    sql += STREAM_TABLE_TEMPLATE.format(stream_table=stream_table)
    return sql


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate holoscrape MySQL schema")
    parser.add_argument("--nshards", type=int, default=30, help="Number of shards (default: 30)")
    parser.add_argument("--table", default="chat_tab", help="Chat table prefix (default: chat_tab)")
    parser.add_argument("--stream-table", default="stream_tab", help="Stream table name (default: stream_tab)")
    parser.add_argument("-o", "--output", default=None, help="Output file (default: stdout)")
    args = parser.parse_args()

    sql = generate(args.nshards, args.table, args.stream_table)

    if args.output:
        with open(args.output, "w") as f:
            f.write(sql)
        print(f"Wrote {args.output}", file=sys.stderr)
    else:
        print(sql)


if __name__ == "__main__":
    main()
