-- holoscrape database schema
-- Generated by generate_init_sql.py
-- Shards: 30, chat table: chat_tab, stream table: stream_tab

CREATE USER 'holoscrape'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON holoscrape.* TO 'holoscrape'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS holoscrape;
USE holoscrape;

CREATE TABLE IF NOT EXISTS chat_tab_0 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_1 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_2 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_3 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_4 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_5 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_6 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_7 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_8 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_9 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_10 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_11 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_12 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_13 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_14 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_15 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_16 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_17 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_18 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_19 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_20 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_21 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_22 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_23 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_24 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_25 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_26 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_27 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_28 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS chat_tab_29 (
	video_id VARCHAR(255),
	chat_id VARCHAR(255) NOT NULL PRIMARY KEY,
	text VARCHAR(255),
	timestamp VARCHAR(255),
	author_name VARCHAR(255),
	author_id VARCHAR(255),
	source VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS stream_tab (
	id VARCHAR(255) NOT NULL PRIMARY KEY,
	title VARCHAR(255),
	topic_id VARCHAR(255),
	channel_id VARCHAR(255),
	channel_name VARCHAR(255)
);
